require_relative 'lib/utils.rb'
require_relative 'lib/xamarin/xamarin_solution.rb'

default_platform :ios

platform :ios do

  before_all do
    @config = {}
    FastlaneCore::XamarinSolution.detect_solutions(@config)
    @solution = FastlaneCore::XamarinSolutionParser.parse(@config[:xamarin_solution])

    restore_nugets(@config[:xamarin_solution])
    restore_xamarin_components(@config[:xamarin_solution], "xamarinqa@gmail.com")
  end

  desc "Runs all the tests"
  lane :test do
    nunit_project = @solution.unit_test_projects.first
    uitests_project = @solution.ui_test_projects.first

    run_nunit_tests(nunit_project)
    run_ui_tests(@config[:xamarin_solution])
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # Provision machine with certs and profiles required for App Store deployment
    match(
      app_identifier: ["com.xamarin.Coffee"],
      type: "appstore",
      username: "xamarinqa@gmail.com,",
      readonly: true,
      team_name: "ZYWNCWEKU5"
    )

    # Bump Info.plist
    bump_version_minor(@solution)

    # Build ipa
    ipa_path = build_for_release(@solution.ios_projects.first)
    pilot(
      ipa: ipa_path,
      username: "xamarinqa@gmail.com"
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end

end